### ISSUE TITLE
Change of output script does not always take effect on other apps

### ISSUE THREAD

**Issue by deepestblue** [ratreya/Lipika_IME#11]
I don't know if this by-design for OS X.

1. Launch 2 apps, say Terminal and Chrome.
1. While Terminal has focus, switch to Lipika as the IME. Let's say Devanagari is the selected output script.
1. Start typing in Terminal; observe Devanagari.
1. Switch to Chrome.
1. Go to Lipika and change the output script to, say, Tamil.
1. Switch back to Terminal.
1. Start typing.

Expected: Tamil output
Actual: Devanagari output

**Comment by ratreya** [comment]
Nice catch! In any case, the behavior is inconsistent because at step 6, the LipikaIME menu shows Tamil as the output script but actually produces Devanagari. I'll take a look at this over the weekend. I am leaning towards making any user-initiated change global to the system because per-application language management can get messy. Thanks for reporting.

**Comment by deepestblue** [comment]
> I am leaning towards making any user-initiated change global to the system because per-application language management can get messy.

I'm OK with either. Windows IMEs are per-application (actually, per window) as that's what the OS supports. "Fake" IMEs that install keyboard-hooks (like Ajit's MudgalaIME) are global. I'm curious how other OS X IMEs function, or rather, what support OS X provides, I guess.

**Comment by ratreya** [comment]
Mac OS X supports per text-input level controls. But the problem I have with per-window or per-application level configuration is that the setting is not readily discoverable on switching an another application. The fix make this configuration global.
