### ISSUE TITLE
Allow latin as one of the options in the dropdown

### ISSUE THREAD

**Issue by trivedigaurav** [ratreya/Lipika_IME#13]
It would be useful to include the text as it as one of the dropdown options when including a English word in the middle, which often comes up as I type in Hindi...

**Comment by ratreya** [comment]
The effort needed to change Input Source is about the same if not less than that needed to change output script in Lipika and hence this was not implemented. The fastest way to shift to English briefly and then back is to make a keyboard shortcut to change Input Sources under System Preferences --> Keyboard --> Shortcuts --> Input Sources as shown below:
![screen shot 2015-05-16 at 7 46 19 am](https://cloud.githubusercontent.com/assets/3529167/7666568/abd789f8-fb9f-11e4-89b3-ca6b8933ddd4.png)
Then assuming you have Lipika and US/UK as your two Input Sources, pressing command-2 will toggle between them. I use command-2 because command-1 conflicts with other shortcuts in Eclipse for example. Hope this helps.
